/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum AddFriendResult
  {
    ESuccess = 0,
    EAddFriendFail = 1,
    EDoNotAddSelf = 2,
    EAddFriendRepeat = 3,
  }
}
