/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Protol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSGetReplay : TBase
  {
    private int _roomId;
    private int _influenceStartIndex;
    private int _influenceCount;

    public int RoomId
    {
      get
      {
        return _roomId;
      }
      set
      {
        __isset.roomId = true;
        this._roomId = value;
      }
    }

    public int InfluenceStartIndex
    {
      get
      {
        return _influenceStartIndex;
      }
      set
      {
        __isset.influenceStartIndex = true;
        this._influenceStartIndex = value;
      }
    }

    public int InfluenceCount
    {
      get
      {
        return _influenceCount;
      }
      set
      {
        __isset.influenceCount = true;
        this._influenceCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roomId;
      public bool influenceStartIndex;
      public bool influenceCount;
    }

    public CSGetReplay() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.I32) {
                RoomId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.I32) {
                InfluenceStartIndex = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 30:
              if (field.Type == TType.I32) {
                InfluenceCount = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("CSGetReplay");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.roomId) {
          field.Name = "roomId";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RoomId);
          oprot.WriteFieldEnd();
        }
        if (__isset.influenceStartIndex) {
          field.Name = "influenceStartIndex";
          field.Type = TType.I32;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(InfluenceStartIndex);
          oprot.WriteFieldEnd();
        }
        if (__isset.influenceCount) {
          field.Name = "influenceCount";
          field.Type = TType.I32;
          field.ID = 30;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(InfluenceCount);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("CSGetReplay(");
      bool __first = true;
      if (__isset.roomId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoomId: ");
        __sb.Append(RoomId);
      }
      if (__isset.influenceStartIndex) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InfluenceStartIndex: ");
        __sb.Append(InfluenceStartIndex);
      }
      if (__isset.influenceCount) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InfluenceCount: ");
        __sb.Append(InfluenceCount);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
