/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum CSLoginResult
  {
    ESuccess = 0,
    EAccountNotExist = 1,
    EAccountError = 2,
    EPasswordError = 3,
    EAccountAlreadyLogged = 4,
  }
}
