/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum DownloadAssetType
  {
    ConfigByte = 0,
    Image = 1,
    Audio = 2,
    AssetBundle = 3,
  }
}
