/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum JoinRoomResult
  {
    ESuccess = 0,
    EJoinRoomFail = 1,
    EAlreadyInRoom = 2,
    ENotInRoom = 3,
  }
}
