/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum RDFindByNickNameResult
  {
    ESuccess = 0,
    EUserError = 1,
  }
}
