/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Protol
{
  public enum RoomStatus
  {
    STATUS_CLOSE = 0,
    STATUS_FULL = 1,
    STATUS_OK = 2,
    STATUS_START = 3,
    STATUS_READY = 4,
    STATUS_RUNNING = 5,
    STATUS_NONE = 6,
  }
}
