/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Protol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCGetRoomList : TBase
  {
    private List<Protol.RoomInfo> _roomList;
    private int _totalCount;

    public List<Protol.RoomInfo> RoomList
    {
      get
      {
        return _roomList;
      }
      set
      {
        __isset.roomList = true;
        this._roomList = value;
      }
    }

    public int TotalCount
    {
      get
      {
        return _totalCount;
      }
      set
      {
        __isset.totalCount = true;
        this._totalCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roomList;
      public bool totalCount;
    }

    public SCGetRoomList() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.List) {
                {
                  RoomList = new List<Protol.RoomInfo>();
                  TList _list36 = iprot.ReadListBegin();
                  for( int _i37 = 0; _i37 < _list36.Count; ++_i37)
                  {
                    Protol.RoomInfo _elem38;
                    _elem38 = new Protol.RoomInfo();
                    _elem38.Read(iprot);
                    RoomList.Add(_elem38);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.I32) {
                TotalCount = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SCGetRoomList");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (RoomList != null && __isset.roomList) {
          field.Name = "roomList";
          field.Type = TType.List;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, RoomList.Count));
            foreach (Protol.RoomInfo _iter39 in RoomList)
            {
              _iter39.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.totalCount) {
          field.Name = "totalCount";
          field.Type = TType.I32;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(TotalCount);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SCGetRoomList(");
      bool __first = true;
      if (RoomList != null && __isset.roomList) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoomList: ");
        __sb.Append(RoomList);
      }
      if (__isset.totalCount) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TotalCount: ");
        __sb.Append(TotalCount);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
