/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "command_constants.h"

namespace CytxGame {

const commandConstants g_command_constants;

commandConstants::commandConstants() {
}

} // namespace

