/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef config_CONSTANTS_H
#define config_CONSTANTS_H

#include "config_types.h"



class configConstants {
 public:
  configConstants();

};

extern const configConstants g_config_constants;



#endif
