/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cs_struct_CONSTANTS_H
#define cs_struct_CONSTANTS_H

#include "cs_struct_types.h"



class cs_structConstants {
 public:
  cs_structConstants();

};

extern const cs_structConstants g_cs_struct_constants;



#endif
