/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CsMsgId_constants.h"



const CsMsgIdConstants g_CsMsgId_constants;

CsMsgIdConstants::CsMsgIdConstants() {
}



