/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Map_CONSTANTS_H
#define Map_CONSTANTS_H

#include "Map_types.h"



class MapConstants {
 public:
  MapConstants();

};

extern const MapConstants g_Map_constants;



#endif
