/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "message_constants.h"

namespace CytxGame {

const messageConstants g_message_constants;

messageConstants::messageConstants() {
}

} // namespace

