/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef profile_CONSTANTS_H
#define profile_CONSTANTS_H

#include "profile_types.h"

namespace CytxGame {

class profileConstants {
 public:
  profileConstants();

};

extern const profileConstants g_profile_constants;

} // namespace

#endif
