/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "template_constants.h"

namespace CytxGame {

const templateConstants g_template_constants;

templateConstants::templateConstants() {
}

} // namespace

