/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef version_CONSTANTS_H
#define version_CONSTANTS_H

#include "version_types.h"



class versionConstants {
 public:
  versionConstants();

};

extern const versionConstants g_version_constants;



#endif
