/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CLoginGame : TBase
  {
    private int _accountId;
    private string _sessionKey;

    public int AccountId
    {
      get
      {
        return _accountId;
      }
      set
      {
        __isset.accountId = true;
        this._accountId = value;
      }
    }

    public string SessionKey
    {
      get
      {
        return _sessionKey;
      }
      set
      {
        __isset.sessionKey = true;
        this._sessionKey = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool accountId;
      public bool sessionKey;
    }

    public CLoginGame() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.I32) {
                AccountId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.String) {
                SessionKey = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("CLoginGame");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.accountId) {
          field.Name = "accountId";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(AccountId);
          oprot.WriteFieldEnd();
        }
        if (SessionKey != null && __isset.sessionKey) {
          field.Name = "sessionKey";
          field.Type = TType.String;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(SessionKey);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("CLoginGame(");
      bool __first = true;
      if (__isset.accountId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AccountId: ");
        __sb.Append(AccountId);
      }
      if (SessionKey != null && __isset.sessionKey) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SessionKey: ");
        __sb.Append(SessionKey);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
