/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum CommandTargetType
  {
    Server = 0,
    Others = 1,
    OthersBuffered = 2,
    All = 3,
    AllBuffered = 4,
  }
}
