/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum CSRegisterResult
  {
    ESuccess = 0,
    EAccountError = 1,
    EPasswordError = 2,
    EAccountAlreadyExist = 3,
    ELandingAccount = 4,
  }
}
