/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum CSSetNicknameResult
  {
    ESuccess = 0,
    ENicknameLengthError = 1,
    ENicknameAlreadyExist = 2,
    EFaild = 3,
  }
}
