/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum JoinInstanceResult
  {
    ESuccess = 0,
    ENotFindInstance = 1,
  }
}
