/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PetData : TBase
  {
    private int _petId;
    private int _health;

    public int PetId
    {
      get
      {
        return _petId;
      }
      set
      {
        __isset.petId = true;
        this._petId = value;
      }
    }

    public int Health
    {
      get
      {
        return _health;
      }
      set
      {
        __isset.health = true;
        this._health = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool petId;
      public bool health;
    }

    public PetData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.I32) {
                PetId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.I32) {
                Health = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PetData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.petId) {
          field.Name = "petId";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(PetId);
          oprot.WriteFieldEnd();
        }
        if (__isset.health) {
          field.Name = "health";
          field.Type = TType.I32;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Health);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PetData(");
      bool __first = true;
      if (__isset.petId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PetId: ");
        __sb.Append(PetId);
      }
      if (__isset.health) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Health: ");
        __sb.Append(Health);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
