/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum QuickMatchResult
  {
    ESuccess = 0,
    ETargetNotOnline = 1,
    ETargetNotWaiting = 2,
  }
}
