/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ReplayData : TBase
  {
    private long _timeData;
    private ClassType _classType;
    private int _levelId;
    private int _levelProgress;

    public long TimeData
    {
      get
      {
        return _timeData;
      }
      set
      {
        __isset.timeData = true;
        this._timeData = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="ClassType"/>
    /// </summary>
    public ClassType ClassType
    {
      get
      {
        return _classType;
      }
      set
      {
        __isset.classType = true;
        this._classType = value;
      }
    }

    public int LevelId
    {
      get
      {
        return _levelId;
      }
      set
      {
        __isset.levelId = true;
        this._levelId = value;
      }
    }

    public int LevelProgress
    {
      get
      {
        return _levelProgress;
      }
      set
      {
        __isset.levelProgress = true;
        this._levelProgress = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool timeData;
      public bool classType;
      public bool levelId;
      public bool levelProgress;
    }

    public ReplayData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 20:
              if (field.Type == TType.I64) {
                TimeData = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 30:
              if (field.Type == TType.I32) {
                ClassType = (ClassType)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 40:
              if (field.Type == TType.I32) {
                LevelId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 50:
              if (field.Type == TType.I32) {
                LevelProgress = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ReplayData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.timeData) {
          field.Name = "timeData";
          field.Type = TType.I64;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(TimeData);
          oprot.WriteFieldEnd();
        }
        if (__isset.classType) {
          field.Name = "classType";
          field.Type = TType.I32;
          field.ID = 30;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)ClassType);
          oprot.WriteFieldEnd();
        }
        if (__isset.levelId) {
          field.Name = "levelId";
          field.Type = TType.I32;
          field.ID = 40;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(LevelId);
          oprot.WriteFieldEnd();
        }
        if (__isset.levelProgress) {
          field.Name = "levelProgress";
          field.Type = TType.I32;
          field.ID = 50;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(LevelProgress);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ReplayData(");
      bool __first = true;
      if (__isset.timeData) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TimeData: ");
        __sb.Append(TimeData);
      }
      if (__isset.classType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClassType: ");
        __sb.Append(ClassType);
      }
      if (__isset.levelId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LevelId: ");
        __sb.Append(LevelId);
      }
      if (__isset.levelProgress) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LevelProgress: ");
        __sb.Append(LevelProgress);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
