/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCNoticeConfirmInvitation : TBase
  {
    private AutoGen.RoleData _roleData;

    public AutoGen.RoleData RoleData
    {
      get
      {
        return _roleData;
      }
      set
      {
        __isset.roleData = true;
        this._roleData = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roleData;
    }

    public SCNoticeConfirmInvitation() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.Struct) {
                RoleData = new AutoGen.RoleData();
                RoleData.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SCNoticeConfirmInvitation");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (RoleData != null && __isset.roleData) {
          field.Name = "roleData";
          field.Type = TType.Struct;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          RoleData.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SCNoticeConfirmInvitation(");
      bool __first = true;
      if (RoleData != null && __isset.roleData) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoleData: ");
        __sb.Append(RoleData== null ? "<null>" : RoleData.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
