/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCReplayChoose : TBase
  {
    private int _result;
    private AutoGen.LevelData _levelData;
    private AutoGen.ClassType _classType;
    private int _levelId;
    private int _endFrameIndex;

    public int Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }

    public AutoGen.LevelData LevelData
    {
      get
      {
        return _levelData;
      }
      set
      {
        __isset.levelData = true;
        this._levelData = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="AutoGen.ClassType"/>
    /// </summary>
    public AutoGen.ClassType ClassType
    {
      get
      {
        return _classType;
      }
      set
      {
        __isset.classType = true;
        this._classType = value;
      }
    }

    public int LevelId
    {
      get
      {
        return _levelId;
      }
      set
      {
        __isset.levelId = true;
        this._levelId = value;
      }
    }

    public int EndFrameIndex
    {
      get
      {
        return _endFrameIndex;
      }
      set
      {
        __isset.endFrameIndex = true;
        this._endFrameIndex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool result;
      public bool levelData;
      public bool classType;
      public bool levelId;
      public bool endFrameIndex;
    }

    public SCReplayChoose() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.I32) {
                Result = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.Struct) {
                LevelData = new AutoGen.LevelData();
                LevelData.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 30:
              if (field.Type == TType.I32) {
                ClassType = (AutoGen.ClassType)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 40:
              if (field.Type == TType.I32) {
                LevelId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 50:
              if (field.Type == TType.I32) {
                EndFrameIndex = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SCReplayChoose");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.result) {
          field.Name = "result";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Result);
          oprot.WriteFieldEnd();
        }
        if (LevelData != null && __isset.levelData) {
          field.Name = "levelData";
          field.Type = TType.Struct;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          LevelData.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.classType) {
          field.Name = "classType";
          field.Type = TType.I32;
          field.ID = 30;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)ClassType);
          oprot.WriteFieldEnd();
        }
        if (__isset.levelId) {
          field.Name = "levelId";
          field.Type = TType.I32;
          field.ID = 40;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(LevelId);
          oprot.WriteFieldEnd();
        }
        if (__isset.endFrameIndex) {
          field.Name = "endFrameIndex";
          field.Type = TType.I32;
          field.ID = 50;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(EndFrameIndex);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SCReplayChoose(");
      bool __first = true;
      if (__isset.result) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Result: ");
        __sb.Append(Result);
      }
      if (LevelData != null && __isset.levelData) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LevelData: ");
        __sb.Append(LevelData== null ? "<null>" : LevelData.ToString());
      }
      if (__isset.classType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClassType: ");
        __sb.Append(ClassType);
      }
      if (__isset.levelId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LevelId: ");
        __sb.Append(LevelId);
      }
      if (__isset.endFrameIndex) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EndFrameIndex: ");
        __sb.Append(EndFrameIndex);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
