/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace AutoGen
{
  public enum TileType
  {
    None = -1,
    Static = 0,
    Trigger = 1,
    NPC = 2,
    PlayerStart = 3,
    SavePoint = 4,
  }
}
