/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AutoGen
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UnitSyncDataList : TBase
  {
    private List<UnitSyncData> _dataList;

    public List<UnitSyncData> DataList
    {
      get
      {
        return _dataList;
      }
      set
      {
        __isset.dataList = true;
        this._dataList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool dataList;
    }

    public UnitSyncDataList() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.List) {
                {
                  DataList = new List<UnitSyncData>();
                  TList _list19 = iprot.ReadListBegin();
                  for( int _i20 = 0; _i20 < _list19.Count; ++_i20)
                  {
                    UnitSyncData _elem21;
                    _elem21 = new UnitSyncData();
                    _elem21.Read(iprot);
                    DataList.Add(_elem21);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UnitSyncDataList");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (DataList != null && __isset.dataList) {
          field.Name = "dataList";
          field.Type = TType.List;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, DataList.Count));
            foreach (UnitSyncData _iter22 in DataList)
            {
              _iter22.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UnitSyncDataList(");
      bool __first = true;
      if (DataList != null && __isset.dataList) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DataList: ");
        __sb.Append(DataList);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
