/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ItemGeneratorConfigTable : TBase
  {
    private Dictionary<int, ItemGeneratorConfig> _itemGeneratorConfigMap;

    public Dictionary<int, ItemGeneratorConfig> ItemGeneratorConfigMap
    {
      get
      {
        return _itemGeneratorConfigMap;
      }
      set
      {
        __isset.itemGeneratorConfigMap = true;
        this._itemGeneratorConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemGeneratorConfigMap;
    }

    public ItemGeneratorConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.Map) {
                {
                  ItemGeneratorConfigMap = new Dictionary<int, ItemGeneratorConfig>();
                  TMap _map47 = iprot.ReadMapBegin();
                  for( int _i48 = 0; _i48 < _map47.Count; ++_i48)
                  {
                    int _key49;
                    ItemGeneratorConfig _val50;
                    _key49 = iprot.ReadI32();
                    _val50 = new ItemGeneratorConfig();
                    _val50.Read(iprot);
                    ItemGeneratorConfigMap[_key49] = _val50;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ItemGeneratorConfigTable");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ItemGeneratorConfigMap != null && __isset.itemGeneratorConfigMap) {
          field.Name = "itemGeneratorConfigMap";
          field.Type = TType.Map;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ItemGeneratorConfigMap.Count));
            foreach (int _iter51 in ItemGeneratorConfigMap.Keys)
            {
              oprot.WriteI32(_iter51);
              ItemGeneratorConfigMap[_iter51].Write(oprot);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ItemGeneratorConfigTable(");
      bool __first = true;
      if (ItemGeneratorConfigMap != null && __isset.itemGeneratorConfigMap) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ItemGeneratorConfigMap: ");
        __sb.Append(ItemGeneratorConfigMap);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
